export const FETCH_STUDENT_REQUEST_DELETE = "FETCH_STUDENT_REQUEST_DELETE";
export const FETCH_STUDENT_SUCCESS_DELETE = "FETCH_STUDENT_SUCCESS_DELETE";
export const FETCH_STUDENT_ERROR_DELETE = "FETCH_STUDENT_ERROR_DELETE";

export const FETCH_STUDENT_REQUEST_PUT = "FETCH_STUDENT_REQUEST_PUT";
export const FETCH_STUDENT_SUCCESS_PUT = "FETCH_STUDENT_SUCCESS_PUT";
export const FETCH_STUDENT_ERROR_PUT = "FETCH_STUDENT_ERROR_PUT";

export const FETCH_STUDENT_REQUEST_PATCH = "FETCH_STUDENT_REQUEST_PATCH";
export const FETCH_STUDENT_SUCCESS_PATCH = "FETCH_STUDENT_SUCCESS_PATCH";
export const FETCH_STUDENT_ERROR_PATCH = "FETCH_STUDENT_ERROR_PATCH";

export const FETCH_STUDENT_REQUEST_POST = "FETCH_STUDENT_REQUEST_POST";
export const FETCH_STUDENT_SUCCESS_POST = "FETCH_STUDENT_SUCCESS_POST";
export const FETCH_STUDENT_ERROR_POST = "FETCH_STUDENT_ERROR_POST";

export const FETCH_STUDENT_SUCCESS_GET = "FETCH_STUDENT_SUCCESS_GET";
export const FETCH_STUDENT_ERROR_GET = "FETCH_STUDENT_ERROR_GET";
export const FETCH_STUDENT_REQUEST_GET = "FETCH_STUDENT_REQUEST_GET";

export const FETCH_STUDENTLIST_SUCCESS_GET = "FETCH_STUDENTLIST_SUCCESS_GET";
export const FETCH_STUDENTLIST_ERROR_GET = "FETCH_STUDENTLIST_ERROR_GET";
export const FETCH_STUDENTLIST_REQUEST_GET = "FETCH_STUDENTLIST_REQUEST_GET";
