export const FETCH_PERIOD_REQUEST_DELETE = "FETCH_PERIOD_REQUEST_DELETE";
export const FETCH_PERIOD_SUCCESS_DELETE = "FETCH_PERIOD_SUCCESS_DELETE";
export const FETCH_PERIOD_ERROR_DELETE = "FETCH_PERIOD_ERROR_DELETE";

export const FETCH_PERIOD_REQUEST_PUT = "FETCH_PERIOD_REQUEST_PUT";
export const FETCH_PERIOD_SUCCESS_PUT = "FETCH_PERIOD_SUCCESS_PUT";
export const FETCH_PERIOD_ERROR_PUT = "FETCH_PERIOD_ERROR_PUT";

export const FETCH_PERIOD_REQUEST_PATCH = "FETCH_PERIOD_REQUEST_PATCH";
export const FETCH_PERIOD_SUCCESS_PATCH = "FETCH_PERIOD_SUCCESS_PATCH";
export const FETCH_PERIOD_ERROR_PATCH = "FETCH_PERIOD_ERROR_PATCH";

export const FETCH_PERIOD_REQUEST_POST = "FETCH_PERIOD_REQUEST_POST";
export const FETCH_PERIOD_SUCCESS_POST = "FETCH_PERIOD_SUCCESS_POST";
export const FETCH_PERIOD_ERROR_POST = "FETCH_PERIOD_ERROR_POST";

export const FETCH_PERIOD_SUCCESS_GET = "FETCH_PERIOD_SUCCESS_GET";
export const FETCH_PERIOD_ERROR_GET = "FETCH_PERIOD_ERROR_GET";
export const FETCH_PERIOD_REQUEST_GET = "FETCH_PERIOD_REQUEST_GET";

export const FETCH_PERIODLIST_SUCCESS_GET = "FETCH_PERIODLIST_SUCCESS_GET";
export const FETCH_PERIODLIST_ERROR_GET = "FETCH_PERIODLIST_ERROR_GET";
export const FETCH_PERIODLIST_REQUEST_GET = "FETCH_PERIODLIST_REQUEST_GET";
