export const FETCH_COURSE_REQUEST_DELETE = "FETCH_COURSE_REQUEST_DELETE";
export const FETCH_COURSE_SUCCESS_DELETE = "FETCH_COURSE_SUCCESS_DELETE";
export const FETCH_COURSE_ERROR_DELETE = "FETCH_COURSE_ERROR_DELETE";

export const FETCH_COURSE_REQUEST_PUT = "FETCH_COURSE_REQUEST_PUT";
export const FETCH_COURSE_SUCCESS_PUT = "FETCH_COURSE_SUCCESS_PUT";
export const FETCH_COURSE_ERROR_PUT = "FETCH_COURSE_ERROR_PUT";

export const FETCH_COURSE_REQUEST_PATCH = "FETCH_COURSE_REQUEST_PATCH";
export const FETCH_COURSE_SUCCESS_PATCH = "FETCH_COURSE_SUCCESS_PATCH";
export const FETCH_COURSE_ERROR_PATCH = "FETCH_COURSE_ERROR_PATCH";

export const FETCH_COURSE_REQUEST_POST = "FETCH_COURSE_REQUEST_POST";
export const FETCH_COURSE_SUCCESS_POST = "FETCH_COURSE_SUCCESS_POST";
export const FETCH_COURSE_ERROR_POST = "FETCH_COURSE_ERROR_POST";

export const FETCH_COURSE_SUCCESS_GET = "FETCH_COURSE_SUCCESS_GET";
export const FETCH_COURSE_ERROR_GET = "FETCH_COURSE_ERROR_GET";
export const FETCH_COURSE_REQUEST_GET = "FETCH_COURSE_REQUEST_GET";

export const FETCH_COURSELIST_SUCCESS_GET = "FETCH_COURSELIST_SUCCESS_GET";
export const FETCH_COURSELIST_ERROR_GET = "FETCH_COURSELIST_ERROR_GET";
export const FETCH_COURSELIST_REQUEST_GET = "FETCH_COURSELIST_REQUEST_GET";
