export const FETCH_STAFF_REQUEST_PATCH = "FETCH_STAFF_REQUEST_PATCH";
export const FETCH_STAFF_SUCCESS_PATCH = "FETCH_STAFF_SUCCESS_PATCH";
export const FETCH_STAFF_ERROR_PATCH = "FETCH_STAFF_ERROR_PATCH";

export const FETCH_STAFF_REQUEST_DELETE = "FETCH_STAFF_REQUEST_DELETE";
export const FETCH_STAFF_SUCCESS_DELETE = "FETCH_STAFF_SUCCESS_DELETE";
export const FETCH_STAFF_ERROR_DELETE = "FETCH_STAFF_ERROR_DELETE";

export const FETCH_STAFF_REQUEST_PUT = "FETCH_STAFF_REQUEST_PUT";
export const FETCH_STAFF_SUCCESS_PUT = "FETCH_STAFF_SUCCESS_PUT";
export const FETCH_STAFF_ERROR_PUT = "FETCH_STAFF_ERROR_PUT";

export const FETCH_STAFF_REQUEST_POST = "FETCH_STAFF_REQUEST_POST";
export const FETCH_STAFF_SUCCESS_POST = "FETCH_STAFF_SUCCESS_POST";
export const FETCH_STAFF_ERROR_POST = "FETCH_STAFF_ERROR_POST";

export const FETCH_STAFF_SUCCESS_GET = "FETCH_STAFF_SUCCESS_GET";
export const FETCH_STAFF_ERROR_GET = "FETCH_STAFF_ERROR_GET";
export const FETCH_STAFF_REQUEST_GET = "FETCH_STAFF_REQUEST_GET";

export const FETCH_STAFFLIST_SUCCESS_GET = "FETCH_STAFFLIST_SUCCESS_GET";
export const FETCH_STAFFLIST_ERROR_GET = "FETCH_STAFFLIST_ERROR_GET";
export const FETCH_STAFFLIST_REQUEST_GET = "FETCH_STAFFLIST_REQUEST_GET";
